# This is a basic workflow to help you get started with Actions

name: ImageMagick Updater Bot

# Controls when the workflow will run
on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  createPullRequest:
    name: Update ImageMagick with Pull Request
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6

      - name: Disable git advice
        run: git config --global advice.detachedHead false

      - name: Make changes to pull request
        id: imupdater
        continue-on-error: true
        run: ./.github-deps/imupdate/update-magick.ps1

      - name: Create Pull Request
        id: cpr
        if: steps.imupdater.outcome == 'success' && steps.imupdater.conclusion == 'success'
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ secrets.REPO_SCOPED_TOKEN }}
          commit-message: Update ImageMagick from ${{ steps.imupdater.outputs.OldVersion }} -> ${{ steps.imupdater.outputs.NewVersion }}
          committer: GitHub <noreply@github.com>
          author: GitHub <noreply@github.com>
          signoff: false
          branch: imupdate
          delete-branch: true
          title: 'Update ImageMagick to ${{ steps.imupdater.outputs.NewVersion }}'
          body: |
            Hey there!
            
            I just found an upstream ImageMagick update and made the source code changes for you.
            
            ImageMagick in this project has been updated from ${{ steps.imupdater.outputs.OldVersion }} -> ${{ steps.imupdater.outputs.NewVersion }}
            
            If the build succeeds, I'll just auto-merge it for you :wink:
            
            **_[ This was automatically generated by github-actions[bot] ]_**
          labels: |
            update
            automated pr
          assignees: |
            ${{ github.actor == 'MrR0b0X' && 'MrR0b0X' || github.actor == 'molotovcherry' && 'molotovcherry' || '' }}
          draft: false

      - name: Check outputs
        if: steps.imupdater.outcome == 'success' && steps.imupdater.conclusion == 'success'
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"

      - name: Enable Pull Request Automerge
        if: steps.cpr.outputs.pull-request-operation == 'created' && steps.imupdater.outcome == 'success' && steps.imupdater.conclusion == 'success'
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.REPO_SCOPED_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: rebase
